#!/bin/bash

# Dieses Skript konvertiert audible-Dateien (aa) in mp3.
# Die Audible Dateien müssen im "Format 4" (aa) heruntergeladen werden.
#
# This script convert audible aa files to mp3 files
# First download the audible files in "Format 4" (aa).
#
# You need to be running Nautilus 1.0.3+ to use scripts.
# Install for local user in ~/.local/share/nautilus/scripts
# To install  for all users, type:
# sudo cp audible_to_mp3.sh /usr/share/nautilus-scripts
# sudo chmod +x /usr/share/nautilus-scripts/audible_to_mp3.sh
# sudo ln -s /usr/share/nautilus-scripts/audible_to_mp3.sh ~/.local/share/nautilus/scripts/audible_to_mp3
#
# dependent on: ffmpeg
#
# Author: Joerg Sorge
# Distributed under the terms of GNU GPL version 2 or later
# Copyright (C) Joerg Sorge joergsorge at gmail.com
# 2018-05-22


function f_choose_msg_lang () {
	local_locale=$(locale | grep LANGUAGE | cut -d= -f2 | cut -d_ -f1)
	if [ $local_locale == "de" ]; then
		msg[1]="installiert"
		msg[2]="Konvertieren zu mp3..."
		msg[3]="none..."
		msg[4]="x zu mp3: Bearbeite Dateien..."
		msg[5]="Abgebrochen..."

		err[1]=" ist nicht installiert, Bearbeitung nicht moeglich."
		err[2]="Das ist keine aa Datei:"
		err[3]="Fehler beim Transkodieren"
		err[4]="Fehler beim Transkodieren"
	else
		msg[1]="installed"
		msg[2]="Converting to mp3..."
		msg[3]="none..."
		msg[4]="x to mp3: work on files..."
		msg[5]="Canceled..."

		err[1]=" not installed, work not possible."
		err[2]="It's not a aa file:"
		err[3]="Error by converting to mp3 "
		err[4]="Error by mp3gain"
	fi
}


function f_check_package () {
	package_install=$1
	if dpkg-query -s $1 2>/dev/null|grep -q installed; then
		echo "$package_install ${msg[1]}"
	else
		zenity --error --text="$package_install ${err[1]}"
		exit
	fi
}

# switch lang
f_choose_msg_lang
# check for packages
f_check_package "ffmpeg"

# this works not properly if multible files are selected
# echo -n "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | while read file ; do
# so we use this loop

for file in "$@"; do
report "tomp3"
(
	filename=$(basename "$file")
	extension="${filename##*.}"
	# echo and progress will pulsate
	echo "10"
	echo "# ${msg[2]}\n$filename"

	if [ "$extension" != "aa" ] && [ "$extension" != "AA" ]; then
		zenity --error --text="${err[2]}\n$filename"
		exit
	fi

	message=$(ffmpeg -y -i "$file" -codec copy "${file%%.*}.mp3" 2>&1 && echo "Success")
	# remove all characters right from 'S'
	error=${message##*S}
	if [ "$error" != "uccess" ]
		then
		echo "$message" | zenity --title="${err[3]} " --text-info --width=500 --height=200
	fi

) | zenity --progress \
           --title="${msg[4]}" --text="..." --width=500 --pulsate --auto-close

if [ "$?" = -1 ] ; then
	zenity --error --text="${msg[5]}"
fi
done
exit
