#!/bin/bash

## Dieses Skript normalisiert Audio-Dateien auf - 2 dB
## sox mit mp3-Support muss installiert sein.
#
# This script normalize audio files.
#
# You need to be running Nautilus 1.0.3+ to use scripts.
# To install as Nautilus script consider copying to filename with spaces.
# This is for better reading the Nautilus content menu
# For all users, type for example:
# sudo cp my_script "/usr/share/nautilus-scripts/my script"
# sudo chmod +x "/usr/share/nautilus-scripts/my script"
# sudo ln -s "/usr/share/nautilus-scripts/my_script" "~/.local/share/nautilus/scripts/my script"
#
# For local user, type for example:
# cp my_script ".local/share/nautilus/scripts/my script"
# chmod u+x ".local/share/nautilus/scripts/my script"
#
# dependent on: sox, libsox-fmt-mp3
# if not alraedy on your system, type for example:
# sudo apt-get install sox libsox-fmt-mp3
#
#
#
# Author: Joerg Sorge
# Distributed under the terms of GNU GPL version 2 or later
# Copyright (C) Joerg Sorge joergsorge @ g mail
# 2017-03-29

function f_choose_msg_lang () {
	local_locale=$(locale | grep LANGUAGE | cut -d= -f2 | cut -d_ -f1)
	if [ $local_locale == "de" ]; then
		msg[1]="installiert"
		msg[2]="Normalisieren..."
		msg[3]="replayGain berechnen..."
		msg[4]="Normalisieren: Bearbeite Dateien..."
		msg[5]="Abgebrochen..."

		err[1]=" ist nicht installiert, Bearbeitung nicht moeglich."
		err[2]="Das ist keine mp3 Datei:"
		err[3]="Fehler beim Normalisieren"
	else
		msg[1]="installed"
		msg[2]="Normalize..."
		msg[3]="Calculate replayGain..."
		msg[4]="Normalize: work on files..."
		msg[5]="Canceled..."

		err[1]=" not installed, work not possible."
		err[2]="It's not a mp3 file:"
		err[3]="Error by normalizing "
	fi
}


function f_check_package () {
	package_install=$1
	if dpkg-query -s $1 2>/dev/null|grep -q installed; then
		echo "$package_install ${msg[1]}"
	else
		zenity --error --text="$package_install ${err[1]}"
		exit
	fi
}

# switch lang
f_choose_msg_lang
# check for packages
f_check_package "sox"
f_check_package "libsox-fmt-mp3"


echo -n "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | while read file ; do

report "normalizer"
(
	filename=$(basename "$file")
	extension="${filename##*.}"
	# echo and progress will pulsate
	echo "10"
	echo "# ${msg[2]}\n$filename"

	if [ "$extension" != "mp3" ] && [ "$extension" != "MP3" ]; then
		zenity --error --text="${err[2]}\n$filename"
		exit
	fi

	# copy original file in to subfolder
	mkdir -p original
	path_source=$(dirname "$file")
	file_path_orig="$path_source/original/$filename"
	cp "$file" "$file_path_orig"

	echo "# ${msg[2]}\n$filename"
	message=$(sox "$file_path_orig" --norm=-2 "$file" 2>&1 && echo "Success")
	# alle zeichen von rechts nach dem 'S' fuer fehleranalyse extrahieren
	error=${message##*S}
	if [ "$error" != "uccess" ]
		then
		echo "$message" | zenity --title="${err[3]}" --text-info --width=500 --height=200
	fi

) | zenity --progress \
           --title="${msg[4]}" --text="..." --width=500 --pulsate --auto-close

if [ "$?" = -1 ] ; then
	zenity --error --text="${msg[5]}"
fi
done
exit
